<?php

$listgroup = '
<div class="list-group"> 
<a href="chat.php" class="list-group-item"> 
<h4 class="list-group-item-heading">Chat</h4> 
<p class="list-group-item-text">Just a group chat</p>
</a>
<a href="addteam.php" class="list-group-item"> 
<h4 class="list-group-item-heading">Add Team</h4> 
<p class="list-group-item-text">Fill in information and upload an image about a team</p> 
</a> 
<a href="viewteams.php" class="list-group-item"> 
<h4 class="list-group-item-heading">View Teams</h4> 
<p class="list-group-item-text">See a list of the added teams</p> </a>
		<a href="matchscout.php" class="list-group-item"> <h4 class="list-group-item-heading">Match Scout</h4> <p class="list-group-item-text">Keep statistics about teams</p> </a>
		<a href="adduser.php" class="list-group-item"> <h4 class="list-group-item-heading">Add User</h4> <p class="list-group-item-text">Add user to database</p> </a>
		<a href="stats.php" class="list-group-item"> <h4 class="list-group-item-heading">Stats</h4> <p class="list-group-item-text">Match info about each team</p> </a>
		<!--<a href="sql.php" class="list-group-item"> <h4 class="list-group-item-heading">SQL Terminal</h4> <p class="list-group-item-text">Control the database</p> </a>//-->
		</div>';