<!DOCTYPE html>
<html lang="en">
<head>
<style>
body {padding-top:70px !important;}
</style>
<meta charset="utf-8">
<title>Titanium Titans Scouting</title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<link rel="stylesheet" href="css/bootstrap.css" media="screen">
<link rel="stylesheet" href="css/bootswatch.min.css">
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]><script src="js/html5shiv.js"></script><script src="js/respond.min.js"></script><script src="http://cdnjs.cloudflare.com/ajax/libs/fastclick/0.6.7/fastclick.min.js"></script><![endif]-->
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
<div class="container"><div class="navbar-header">
<a href="choose.php" class="navbar-brand">Titanium Titans Scouting</a>
</div>
</div>
</div>
<div class="container" id="maincontainer">

<?php echo $content; ?>

</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootswatch.js"></script>
</body>
</html>